#!/bin/bash

echo "🚀 Debuggle VS Code Extension Setup"
echo "===================================="

echo "📦 Extension is compiled and ready!"
echo "✅ TypeScript compiled successfully"
echo ""
echo "🎯 INSTALLATION OPTIONS:"
echo ""
echo "OPTION 1: Development Mode (Recommended for now)"
echo "1. Open VS Code"
echo "2. Press Ctrl+Shift+P"
echo "3. Type 'Extensions: Install from VSIX'"
echo "4. Navigate to: /home/mikej/debuggle/vscode-extension/"
echo "5. OR simply open the vscode-extension folder in VS Code and press F5"
echo ""
echo "OPTION 2: Load Extension Directly"
echo "1. Open VS Code"
echo "2. Go to File > Open Folder"
echo "3. Open: /home/mikej/debuggle/vscode-extension/"
echo "4. Press F5 to launch Extension Development Host"
echo "5. A new VS Code window will open with the extension loaded"
echo ""
echo "🔧 Extension Features:"
echo "- Real-time error monitoring from Debuggle server"
echo "- Problems panel integration"
echo "- Status bar monitoring"
echo "- Dashboard view"
echo "- Command palette integration"
echo ""
echo "📡 Next Steps:"
echo "1. Start Debuggle server: cd /home/mikej/debuggle && python entry_point.py serve"
echo "2. Open VS Code with the extension loaded"
echo "3. Use Ctrl+Shift+P > 'Debuggle: Start Monitoring'"
echo ""
echo "✅ Setup complete! Extension ready for development use."