#!/bin/bash

echo "🚀 VS Code Extension Loading Guide"
echo "=================================="
echo ""
echo "📋 CURRENT STATUS:"
echo "✅ Debuggle server running on http://localhost:8000"
echo "✅ WebSocket connection established"
echo "✅ Extension compiled and ready"
echo ""
echo "🎯 NEXT STEPS:"
echo ""
echo "1. Open VS Code"
echo "2. File → Open Folder → Select this path:"
echo "   /home/mikej/debuggle/vscode-extension/"
echo ""
echo "3. Once the folder is open in VS Code:"
echo "   • Look for the Run and Debug view (Ctrl+Shift+D)"
echo "   • OR simply press F5"
echo "   • This will launch 'Extension Development Host'"
echo ""
echo "4. A NEW VS Code window will open with the extension loaded"
echo ""
echo "5. In the new window, you should see:"
echo "   • Debuggle icon in the status bar (bottom)"
echo "   • Available commands: Ctrl+Shift+P → type 'Debuggle'"
echo ""
echo "🔧 Available Commands in Extension:"
echo "   • Debuggle: Start Monitoring"
echo "   • Debuggle: Show Monitoring Dashboard"
echo "   • Debuggle: Test Connection"
echo "   • Debuggle: Clear All Errors"
echo ""
echo "💡 What You'll See:"
echo "   • Status bar showing error count"
echo "   • Problems panel with 'Debuggle' as source"
echo "   • Real-time error updates as they occur"
echo ""
echo "🧪 To Test the Integration:"
echo "   1. Start monitoring: Ctrl+Shift+P → 'Debuggle: Start Monitoring'"
echo "   2. Generate test errors in another terminal:"
echo "      cd /home/mikej/debuggle"
echo "      python test_errors.py"
echo "   3. Watch errors appear in VS Code Problems panel!"
echo ""
echo "✅ Ready to proceed!"
echo ""
echo "Press any key when you have the extension loaded..."
read -n 1 -s
echo ""
echo "Great! Extension should now be active. Let's test it..."