#!/bin/bash

echo "🖥️  DEBUGGLE VS CODE EXTENSION - WSL SETUP GUIDE"
echo "================================================="
echo ""
echo "📋 CURRENT STATUS:"
echo "✅ Debuggle server running on http://localhost:8000"
echo "✅ Extension compiled and ready"
echo "✅ WSL environment detected"
echo ""
echo "🎯 WSL DEVELOPMENT SETUP (RECOMMENDED)"
echo "======================================"
echo ""
echo "Since you're in WSL, use VS Code's Remote-WSL for best performance:"
echo ""
echo "📁 EXTENSION LOCATION:"
echo "   Default Path: /home/mikej/debuggle/vscode-extension/"
echo "   Windows Path: \\\\wsl\$\\Ubuntu\\home\\mikej\\debuggle\\vscode-extension\\"
echo ""
echo "🚀 OPTION 1: VS Code in WSL (RECOMMENDED)"
echo "----------------------------------------"
echo "1. In this WSL terminal, run:"
echo "   cd /home/mikej/debuggle/vscode-extension"
echo "   code ."
echo ""
echo "2. This opens VS Code connected to WSL with:"
echo "   ✅ Direct file system access"
echo "   ✅ Native WebSocket connections" 
echo "   ✅ Proper path resolution"
echo "   ✅ Same environment as Debuggle server"
echo ""
echo "3. Once VS Code opens:"
echo "   • Press F5 to launch Extension Development Host"
echo "   • New VS Code window opens with extension loaded"
echo ""
echo "🪟 OPTION 2: Windows VS Code (NOT RECOMMENDED)"
echo "---------------------------------------------"
echo "If you must use Windows VS Code:"
echo "1. Open VS Code on Windows"
echo "2. File → Open Folder"
echo "3. Navigate to: \\\\wsl\$\\Ubuntu\\home\\mikej\\debuggle\\vscode-extension\\"
echo "4. ⚠️  May have WebSocket connection issues"
echo "5. ⚠️  Path resolution may not work correctly"
echo ""
echo "🔧 AVAILABLE COMMANDS AFTER LOADING:"
echo "====================================="
echo "Press Ctrl+Shift+P in the Extension Development Host window:"
echo "   • Debuggle: Start Monitoring"
echo "   • Debuggle: Show Monitoring Dashboard" 
echo "   • Debuggle: Test Connection"
echo "   • Debuggle: Clear All Errors"
echo ""
echo "💡 WHAT YOU'LL SEE:"
echo "=================="
echo "   • Status bar: Debuggle icon with error count"
echo "   • Problems panel: 'Debuggle' as error source"
echo "   • Real-time updates as errors occur"
echo ""
echo "🧪 TESTING THE INTEGRATION:"
echo "=========================="
echo "1. Start monitoring: Ctrl+Shift+P → 'Debuggle: Start Monitoring'"
echo "2. In another WSL terminal:"
echo "   cd /home/mikej/debuggle"
echo "   source .venv/bin/activate"
echo "   python test_vscode_integration.py 2>&1 | python cli/debuggle_cli.py"
echo "3. Watch errors appear in VS Code Problems panel!"
echo ""
echo "🔍 TROUBLESHOOTING:"
echo "=================="
echo "• Server not connecting? Run: curl http://localhost:8000"
echo "• Extension not loading? Check: npm run compile worked"
echo "• WebSocket issues? Use WSL VS Code (Option 1)"
echo ""
echo "✅ RECOMMENDED COMMAND TO START:"
echo "cd /home/mikej/debuggle/vscode-extension && code ."
echo ""
echo "Ready to proceed? (Press Enter to continue)"
read