#!/bin/bash

echo "🔧 VS Code Extension Launch Fix"
echo "==============================="
echo ""
echo "✅ Fixed VS Code configuration files:"
echo "   • Updated .vscode/tasks.json with proper task labels"
echo "   • Fixed .vscode/launch.json preLaunchTask reference"
echo "   • Added alternative launch configuration"
echo ""
echo "🚀 How to Launch the Extension:"
echo ""
echo "OPTION 1: Use F5 (Recommended)"
echo "------------------------------"
echo "1. Make sure VS Code has the vscode-extension folder open"
echo "2. Press F5"
echo "3. Select 'Run Extension' if prompted"
echo "4. New Extension Development Host window will open"
echo ""
echo "OPTION 2: Use Run and Debug Panel"
echo "--------------------------------"
echo "1. Open Run and Debug panel (Ctrl+Shift+D)"
echo "2. Select 'Run Extension' from dropdown"
echo "3. Click the green play button"
echo ""
echo "OPTION 3: Manual Compile + Launch"
echo "--------------------------------"
echo "If F5 still doesn't work:"
echo "1. Open terminal in VS Code (Ctrl+\`)"
echo "2. Run: npm run compile"
echo "3. Use 'Run Extension (No Build)' configuration"
echo ""
echo "🧪 After Extension Loads:"
echo "========================"
echo "In the new Extension Development Host window:"
echo "1. Press Ctrl+Shift+P"
echo "2. Type 'Debuggle: Start Monitoring'"
echo "3. You should see Debuggle commands available"
echo ""
echo "🔍 Troubleshooting:"
echo "=================="
echo "• Task not found? Check .vscode/tasks.json has 'npm: compile' label"
echo "• Extension not loading? Run 'npm run compile' manually first"
echo "• Still issues? Use 'Run Extension (No Build)' configuration"
echo ""
echo "✅ Configuration files updated successfully!"
echo "Now try pressing F5 in VS Code again."